maven and sdlc

diff --git a/.sdlc/ci b/.sdlc/ci
--- a/.sdlc/ci
+++ b/.sdlc/ci
@@ -9,9 +9,16 @@ prj_home="$( cd -P "$( dirname "$sdlc_dir" )" && pwd )"
 
 cd "${prj_home}"
 
-hash mvn 2>/dev/null || {
-  echo 'No Maven executable: aborting'
+[[ -x ./mvnw ]] || {
+  echo 'No Maven wrapper executable: aborting'
   exit 1
 }
 
-mvn --no-transfer-progress --batch-mode --update-snapshots verify -Pci
+# Remote Repository Filtering:
+# allows filtering of Artifact by RemoteRepository based on various criteria
+# ${session.rootDirectory} is mvn placeholder, not a script variable
+# https://maven.apache.org/resolver/remote-repository-filtering.html
+./mvnw -s .mvn/settings.xml --update-snapshots --no-transfer-progress --batch-mode \
+   '-Daether.remoteRepositoryFilter.groupId.basedir=${session.rootDirectory}/.mvn/rrf/' \
+    -Daether.remoteRepositoryFilter.groupId=true \
+     verify -Pci
diff --git a/.sdlc/release b/.sdlc/release
--- a/.sdlc/release
+++ b/.sdlc/release
@@ -20,8 +20,8 @@ hash git 2>/dev/null || {
   exit 1
 }
 
-hash mvn 2>/dev/null || {
-  echo 'No Maven executable: aborting release'
+[[ -x ./mvnw ]] || {
+  echo 'No Maven wrapper executable: aborting release'
   exit 1
 }
 
@@ -40,7 +40,7 @@ BASE=$(git merge-base @ "$upstream")
   exit 1
 }
 
-tag_prefix=''
+tag_prefix='v'
 release_suffix=''
 group_id='com.github.enr'
 artifact_id='system-sources'
@@ -78,14 +78,14 @@ git_dirty=$(git status --porcelain)
   exit 1
 }
 
-mvn org.codehaus.mojo:versions-maven-plugin:set-property -Dproperty=revision "-DnewVersion=${release_version}"
-mvn org.codehaus.mojo:versions-maven-plugin:set "-DgroupId=${group_id}" "-DartifactId=${artifact_id}" "-DnewVersion=${release_version}"
-mvn org.codehaus.mojo:versions-maven-plugin:commit
+./mvnw org.codehaus.mojo:versions-maven-plugin:set-property -Dproperty=revision "-DnewVersion=${release_version}"
+./mvnw org.codehaus.mojo:versions-maven-plugin:set "-DgroupId=${group_id}" "-DartifactId=${artifact_id}" "-DnewVersion=${release_version}"
+./mvnw org.codehaus.mojo:versions-maven-plugin:commit
 git commit -a -m "release ${release_version}"
 git tag "${tag_name}"
-mvn org.codehaus.mojo:versions-maven-plugin:set-property -Dproperty=revision "-DnewVersion=${snapshot_version}"
-mvn org.codehaus.mojo:versions-maven-plugin:set "-DgroupId=${group_id}" "-DartifactId=${artifact_id}" "-DnewVersion=${snapshot_version}"
-mvn org.codehaus.mojo:versions-maven-plugin:commit
+./mvnw org.codehaus.mojo:versions-maven-plugin:set-property -Dproperty=revision "-DnewVersion=${snapshot_version}"
+./mvnw org.codehaus.mojo:versions-maven-plugin:set "-DgroupId=${group_id}" "-DartifactId=${artifact_id}" "-DnewVersion=${snapshot_version}"
+./mvnw org.codehaus.mojo:versions-maven-plugin:commit
 git commit -a -m "${snapshot_commit_prefix} back to snapshot"
 git push
 git push --tags
